---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    release.openshift.io/feature-set: TechPreviewNoUpgrade
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
  name: openshift-rukpak
