---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    release.openshift.io/feature-set: TechPreviewNoUpgrade
  name: crd-validation-webhook
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - list
