---
apiVersion: v1
kind: Service
metadata:
  annotations:
    release.openshift.io/feature-set: TechPreviewNoUpgrade
  name: crd-validation-webhook
  namespace: openshift-crd-validator
spec:
  ports:
    - port: 9443
      protocol: TCP
      targetPort: 9443
  selector:
    app: crd-validation-webhook
