---
apiVersion: v1
kind: Service
metadata:
  annotations:
    release.openshift.io/feature-set: TechPreviewNoUpgrade
  name: core
  namespace: openshift-rukpak
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: core
