---
apiVersion: v1
kind: Service
metadata:
  annotations:
    release.openshift.io/feature-set: TechPreviewNoUpgrade
  name: helm-provisioner
  namespace: openshift-rukpak
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: helm-provisioner
