---
apiVersion: v1
kind: Service
metadata:
  annotations:
    release.openshift.io/feature-set: TechPreviewNoUpgrade
  name: rukpak-webhook-service
  namespace: openshift-rukpak
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app: webhooks
