---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    release.openshift.io/feature-set: TechPreviewNoUpgrade
  name: crd-validation-webhook
  namespace: openshift-crd-validator
spec:
  selector:
    matchLabels:
      app: crd-validation-webhook
  template:
    metadata:
      annotations:
        release.openshift.io/feature-set: TechPreviewNoUpgrade
      labels:
        app: crd-validation-webhook
    spec:
      containers:
        - command:
            - /crdvalidator
          image: quay.io/operator-framework/rukpak:devel
          imagePullPolicy: IfNotPresent
          name: crd-validation-webhook
          resources:
            requests:
              cpu: 1m
              memory: 15Mi
          volumeMounts:
            - mountPath: /etc/admission-webhook/tls
              name: tls
      serviceAccountName: crd-validation-webhook
      volumes:
        - name: tls
          secret:
            secretName: crd-validation-webhook-certificate
