---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    release.openshift.io/feature-set: TechPreviewNoUpgrade
  name: helm-provisioner
  namespace: openshift-rukpak
spec:
  dnsNames:
    - helm-provisioner.openshift-rukpak.svc
    - helm-provisioner.openshift-rukpak.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: rukpak-ca-issuer
  secretName: helm-provisioner-cert
