---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    release.openshift.io/feature-set: TechPreviewNoUpgrade
  name: rukpak-selfsigned-issuer
  namespace: openshift-rukpak
spec:
  selfSigned: {}
