---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  annotations:
    release.openshift.io/feature-set: TechPreviewNoUpgrade
  name: selfsigned
  namespace: openshift-crd-validator
spec:
  selfSigned: {}
