---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  annotations:
    release.openshift.io/feature-set: TechPreviewNoUpgrade
  name: rukpak-selfsigned
  namespace: openshift-rukpak
spec:
  selfSigned: {}
